# Generated by Django 2.0.5 on 2018-12-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseoption',
            name='choice',
        ),
    ]
