# Generated by Django 2.1.5 on 2019-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_plot_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
    ]
