# Generated by Django 2.1.5 on 2019-01-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190129_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.IntegerField(blank=True, verbose_name='position'),
        ),
    ]
