# Generated by Django 2.1.5 on 2019-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190212_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionnaire',
            options={'ordering': ['id']},
        ),
    ]
