# Generated by Django 2.1.5 on 2019-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190217_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default='news/None/no-img.jpg', upload_to='news/')),
                ('dedcription', models.CharField(max_length=500)),
            ],
        ),
    ]
