# Generated by Django 2.1.5 on 2019-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='dedcription',
            new_name='description',
        ),
    ]
