# Generated by Django 2.1.5 on 2019-04-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_choice_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
    ]
