# Generated by Django 2.1.5 on 2019-04-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20190407_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['id']},
        ),
    ]
