# Generated by Django 2.1.5 on 2019-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20190407_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='quizimages/')),
            ],
        ),
    ]
