# Generated by Django 2.0.5 on 2018-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_contactnu'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
