# Generated by Django 2.0.5 on 2018-12-20 16:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agegroup',
            field=models.IntegerField(choices=[(0, 'none'), (1, '10-18 yrs'), (2, '19-25 yrs'), (3, '26-40 yrs'), (4, '40+ yrs')], default=0, verbose_name='agegroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contactnu',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='contactnu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'MALE'), (2, 'FEMALE')], default=0, verbose_name='gender'),
        ),
    ]
