# Generated by Django 2.0.5 on 2018-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181220_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactnu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
